### PR TITLE
Add Password Encryption for User Security

### PR DESCRIPTION
**Pull request by daniell-olaitan**
This PR implements password encryption using `Flask-Bcrypt` to enhance user data security by hashing passwords during user registration.

### CODE REVIEW

**Comment by jmartinpizarro** [comment]
Code seems LGTM... However, let me tell you somethings you can improve:

- If we want to logIn with a user, how can we decypher the key?
- How can be the key safely be stored in our database? It is recommendable to so?
- **USE STANDARD ALGORYTHMS SUCH AES-256** for this cyphering methods.

**Remember**, although this does not need to be profesional, we are trying to do a boilerplate as close as possible as a real-life example problem. There's no need to hurry up, ask any questions if you need help.

Please, try to think about the long-term functionality of this app. Here you have some articles that you can read for more info:

- [Cryptographic Storage Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html)
- [Encryption Key Management: Best Practices for Key Storage and Protection](https://www.hakia.com/encryption-key-management-best-practices-for-key-storage-and-protection/)

**Comment by daniell-olaitan** [comment]
Thank you for the feedback! I'd like to clarify the reasoning behind using `Flask-Bcrypt` for password storage.

- Passwords Should Be Irreversible: When storing passwords, the best practice is to use one-way hashing algorithms like `Bcrypt`, `Argon2`, or `PBKDF2`. These algorithms are designed to hash passwords in a way that cannot be reversed, meaning even if an attacker gets access to the hashed password, they cannot retrieve the original password.

- AES-256 is not Suitable for Passwords: `AES-256` is a symmetric encryption algorithm, which means it can both encrypt and decrypt data. For passwords, we don't want decryption to be possible. Instead, when users log in, the hashed version of the entered password is compared with the stored hash. There’s no need to store an encryption key or decrypt passwords in a properly designed password authentication system.

- Long-term Security: `Bcrypt` is used widely in industry and is a well-tested, secure approach for password storage. It includes key stretching and salting, which helps protect against brute-force attacks and rainbow table attacks.

While `AES-256` is great for encrypting data such as files, personal information, or communication, it's not suitable for password storage. `Flask-Bcrypt` adheres to current industry standards for handling passwords.

Let me know if you'd like me to make any other changes or clarifications!

**Comment by daniell-olaitan** [comment]
When the time comes to implement user login, it is a straight forward process. During user registration, the user password is hashed and the hash is stored in the database. When the user wants to log in, the application will hash the provided password for login, fetches the stored hash and compare them.

**Comment by jmartinpizarro** [comment]
Yup, you were right. 

After researching a little bit I found that for storing passwords in DB is commonly used hash methods. My fault. Everything seems right! Approved! Thanks for your help!!

**Pull request merged**
